id = "st.stm32f429.pwm_demo"
target = "st.stm32f429"
default_config = "debug"

[configs.debug]
resc = "sim.resc"
firmware = "firmware/firmware.elf"

[configs.debug.build]
workdir = "firmware/Debug"
command = ["make", "all"]
artifact = "firmware/Debug/firmware.elf"
